### PR TITLE
Moved the choose file button and classify button

### PR DESCRIPTION
**Pull request by syntux**
- Added 3D look to area where filename is displayed
- Moved convert csv button and current directoy text as well until it is
no longer needed

**Before**
before

**After**
new

### CODE REVIEW

**Review by jtanderson — COMMENTED** [review]
Nice!

**Review by jtanderson — APPROVED** [review]

**Review by jthorntonn — COMMENTED** [review]
comment

**Comment by Edgup** [comment]
Test

**Review by jthorntonn — APPROVED** [review]
comment approved

**Pull request merged**
