### PR TITLE
Updated table, search, and confirm/override buttons

### PR DESCRIPTION
**Pull request by syntux**
- The table did not originally work it now does.
- The table originally had a fixed size of 25, but it is now dynamic.

- The search button could not be clicked, it now works. 

- Search button also deleted all other entries, now saves the data and redraws the table when searching for nothing.
- The confirm and override buttons work but not the way it is intended. Supposed to write to the RDF, but only writes to a text file called prediction.txt for now. 
425 use
- Also the confirm and override buttons give errors if no prediction has been made.

### CODE REVIEW

**Comment by jtanderson** [comment]
@syntux Just a ping to remind to fix the conflicts and update the PR

**Comment by syntux** [comment]
> 
> 
> @syntux Just a ping to remind to fix the conflicts and update the PR

@jtanderson  The conflicts have been fixed but the bug has not since I thought we were going to wait to fix. Do you want me to pull request anyway?

**Comment by jtanderson** [comment]
> > @syntux Just a ping to remind to fix the conflicts and update the PR
> 
> @jtanderson The conflicts have been fixed but the bug has not since I thought we were going to wait to fix. Do you want me to pull request anyway?

Makes sense! I'm fine either way if you think merging would add some features to be beneficial with some remaining issues to be fixed later. What do you think?

**Comment by syntux** [comment]
> 
> 
> > > @syntux Just a ping to remind to fix the conflicts and update the PR
> > 
> > 
> > @jtanderson The conflicts have been fixed but the bug has not since I thought we were going to wait to fix. Do you want me to pull request anyway?
> 
> Makes sense! I'm fine either way if you think merging would add some features to be beneficial with some remaining issues to be fixed later. What do you think?

@jtanderson I think the features are beneficial enough so I have pushed the conflict resolution and am ready to merge. We will just have to take note of the changes needed next semester. The prediction and building a neural network that didn't work now do with my most recent commit. And the table things I've fixed along with Ethan's edit label do work.

**Comment by jtanderson** [comment]
I'm going to merge this for now so we can do some testing/work with this over the summer.

**Pull request merged**
