### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Mhous1**
The function was creating a file in the GUI directory instead of the specific folder containing the model. The parameters were saving to the improper directory with help from Bevan understanding the self.CLASS_NAME (line 334) usability I was able to fix the location where the parameters were saved.
pullreq

### CODE REVIEW

**Comment by jtanderson** [comment]
@Edgup Pinging for secondary review.

**Comment by jtanderson** [comment]
This behavior should be on the "Set Model Parameters" button. The "Set Default Parameters" button can maybe be removed and that functionality moved to a "preferences" menu later?

**Comment by Edgup** [comment]
Looks all good to me!

**Review by Edgup — APPROVED** [review]
Doesn't appear to have any conflicts and/or errors in logic

**Review by jtanderson — APPROVED** [review]

**Pull request merged**
